/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SlackRouteImport } from './routes/slack'
import { Route as StoryRouteImport } from './routes/story'
import { Route as AuthenticatedSlackAdminRouteImport } from './routes/_authenticated/slack-admin'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as BlogBestSlackAppsTeamBuildingRouteImport } from './routes/blog.best-slack-apps-team-building'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as SlackIndexRouteImport } from './routes/slack.index'
import { Route as SlackTeamBuildingRouteImport } from './routes/slack.team-building'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'
import { Route as OauthSlackReturnRouteImport } from './routes/oauth.slack.return'
import { Route as ApiPublicSlackSchedulerRouteImport } from './routes/api/public/slack/scheduler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SlackRoute = SlackRouteImport.update({
  id: '/slack',
  path: '/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSlackAdminRoute = AuthenticatedSlackAdminRouteImport.update({
  id: '/slack-admin',
  path: '/slack-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBestSlackAppsTeamBuildingRoute =
  BlogBestSlackAppsTeamBuildingRouteImport.update({
    id: '/best-slack-apps-team-building',
    path: '/best-slack-apps-team-building',
    getParentRoute: () => BlogRoute,
  } as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SlackIndexRoute = SlackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlackRoute,
} as any)
const SlackTeamBuildingRoute = SlackTeamBuildingRouteImport.update({
  id: '/team-building',
  path: '/team-building',
  getParentRoute: () => SlackRoute,
} as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSlackReturnRoute = OauthSlackReturnRouteImport.update({
  id: '/oauth/slack/return',
  path: '/oauth/slack/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlackSchedulerRoute = ApiPublicSlackSchedulerRouteImport.update({
  id: '/api/public/slack/scheduler',
  path: '/api/public/slack/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slack': typeof SlackRouteWithChildren
  '/story': typeof StoryRoute
  '/slack-admin': typeof AuthenticatedSlackAdminRoute
  '/api/tts': typeof ApiTtsRoute
  '/blog/best-slack-apps-team-building': typeof BlogBestSlackAppsTeamBuildingRoute
  '/s/$token': typeof STokenRoute
  '/slack/team-building': typeof SlackTeamBuildingRoute
  '/slack/': typeof SlackIndexRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/oauth/slack/return': typeof OauthSlackReturnRoute
  '/api/public/slack/scheduler': typeof ApiPublicSlackSchedulerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/slack-admin': typeof AuthenticatedSlackAdminRoute
  '/api/tts': typeof ApiTtsRoute
  '/blog/best-slack-apps-team-building': typeof BlogBestSlackAppsTeamBuildingRoute
  '/s/$token': typeof STokenRoute
  '/slack/team-building': typeof SlackTeamBuildingRoute
  '/slack': typeof SlackIndexRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/oauth/slack/return': typeof OauthSlackReturnRoute
  '/api/public/slack/scheduler': typeof ApiPublicSlackSchedulerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slack': typeof SlackRouteWithChildren
  '/story': typeof StoryRoute
  '/_authenticated/slack-admin': typeof AuthenticatedSlackAdminRoute
  '/api/tts': typeof ApiTtsRoute
  '/blog/best-slack-apps-team-building': typeof BlogBestSlackAppsTeamBuildingRoute
  '/s/$token': typeof STokenRoute
  '/slack/team-building': typeof SlackTeamBuildingRoute
  '/slack/': typeof SlackIndexRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/oauth/slack/return': typeof OauthSlackReturnRoute
  '/api/public/slack/scheduler': typeof ApiPublicSlackSchedulerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/reset-password'
    | '/sitemap.xml'
    | '/slack'
    | '/story'
    | '/slack-admin'
    | '/api/tts'
    | '/blog/best-slack-apps-team-building'
    | '/s/$token'
    | '/slack/team-building'
    | '/slack/'
    | '/api/public/waitlist'
    | '/oauth/slack/return'
    | '/api/public/slack/scheduler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/reset-password'
    | '/sitemap.xml'
    | '/story'
    | '/slack-admin'
    | '/api/tts'
    | '/blog/best-slack-apps-team-building'
    | '/s/$token'
    | '/slack/team-building'
    | '/slack'
    | '/api/public/waitlist'
    | '/oauth/slack/return'
    | '/api/public/slack/scheduler'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/reset-password'
    | '/sitemap.xml'
    | '/slack'
    | '/story'
    | '/_authenticated/slack-admin'
    | '/api/tts'
    | '/blog/best-slack-apps-team-building'
    | '/s/$token'
    | '/slack/team-building'
    | '/slack/'
    | '/api/public/waitlist'
    | '/oauth/slack/return'
    | '/api/public/slack/scheduler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlackRoute: typeof SlackRouteWithChildren
  StoryRoute: typeof StoryRoute
  ApiTtsRoute: typeof ApiTtsRoute
  STokenRoute: typeof STokenRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRoute
  OauthSlackReturnRoute: typeof OauthSlackReturnRoute
  ApiPublicSlackSchedulerRoute: typeof ApiPublicSlackSchedulerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slack': {
      id: '/slack'
      path: '/slack'
      fullPath: '/slack'
      preLoaderRoute: typeof SlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/slack-admin': {
      id: '/_authenticated/slack-admin'
      path: '/slack-admin'
      fullPath: '/slack-admin'
      preLoaderRoute: typeof AuthenticatedSlackAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-slack-apps-team-building': {
      id: '/blog/best-slack-apps-team-building'
      path: '/best-slack-apps-team-building'
      fullPath: '/blog/best-slack-apps-team-building'
      preLoaderRoute: typeof BlogBestSlackAppsTeamBuildingRouteImport
      parentRoute: typeof BlogRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slack/': {
      id: '/slack/'
      path: '/'
      fullPath: '/slack/'
      preLoaderRoute: typeof SlackIndexRouteImport
      parentRoute: typeof SlackRoute
    }
    '/slack/team-building': {
      id: '/slack/team-building'
      path: '/team-building'
      fullPath: '/slack/team-building'
      preLoaderRoute: typeof SlackTeamBuildingRouteImport
      parentRoute: typeof SlackRoute
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/slack/return': {
      id: '/oauth/slack/return'
      path: '/oauth/slack/return'
      fullPath: '/oauth/slack/return'
      preLoaderRoute: typeof OauthSlackReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/scheduler': {
      id: '/api/public/slack/scheduler'
      path: '/api/public/slack/scheduler'
      fullPath: '/api/public/slack/scheduler'
      preLoaderRoute: typeof ApiPublicSlackSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSlackAdminRoute: typeof AuthenticatedSlackAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSlackAdminRoute: AuthenticatedSlackAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogBestSlackAppsTeamBuildingRoute: typeof BlogBestSlackAppsTeamBuildingRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogBestSlackAppsTeamBuildingRoute: BlogBestSlackAppsTeamBuildingRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface SlackRouteChildren {
  SlackTeamBuildingRoute: typeof SlackTeamBuildingRoute
  SlackIndexRoute: typeof SlackIndexRoute
}

const SlackRouteChildren: SlackRouteChildren = {
  SlackTeamBuildingRoute: SlackTeamBuildingRoute,
  SlackIndexRoute: SlackIndexRoute,
}

const SlackRouteWithChildren = SlackRoute._addFileChildren(SlackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlackRoute: SlackRouteWithChildren,
  StoryRoute: StoryRoute,
  ApiTtsRoute: ApiTtsRoute,
  STokenRoute: STokenRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRoute,
  OauthSlackReturnRoute: OauthSlackReturnRoute,
  ApiPublicSlackSchedulerRoute: ApiPublicSlackSchedulerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
